### ISSUE TITLE
Vkladaci / edit formular - rozbit na issues

### ISSUE THREAD

**Issue by mirekys** [Narodni-repozitar/nr-issues#2]
- [x] oznacit predem povinna pole
- [x] taxonomy term pole nevycisti zadany text po vyberu termu
- [x] dalsi nazvy prehodit hned za primarni nazev
- [x] velke pismeno s diakritikou ma skrytou diakritiku
- [x] #28
- [x] moznost zakazat vybrat term s potomky (u napr. licenci)
- [x] datum vydani by mel umoznit zadat jen rok (podle EDTF-0)
- [x] u autoru odebrat vyber roli
- [x] #29
- [x] fixnout 500✅ chybu pri nevyplneni alt identifiers pri rucnim create clanku
- [x] upravit editacni formular pro novy model

**Comment by hanavyc** [comment]
- [ ] chtelo by to specifictejsi hlaseni chyb i kdyz se draft odesila ke schvaleni
- [ ] datum vydani - uz lze dopsat jen rok, ale pri vyberu data z kalendare hazi chybu

**Comment by hanavyc** [comment]
co se tyce te chyby 403, nechavala jsem zpravu na Mattermostu, stalo se to Pete pri vraceni zaznamu ke schvaleni, kolekce byla spravne - NTK
