### ISSUE TITLE
Provozní podmínky/Terms of service

### ISSUE THREAD

**Issue by hanavyc** [Narodni-repozitar/nr-issues#23]
K pilotu toho moc nemám, v zásadě jen 3 body, které jsou v Pravidlech využití služeb DU (https://du.cesnet.cz/cs/provozni_pravidla/start), a mohly by být ve střetu s koncepcí repozitáře. 

1. Data typu archivu nebo záloh (článek 3 v podmínkách) - bude se týkat repozitáře? Repozitářová data by odpovídala asi více typu archivu, tam je ale omezený objem dat a počet souborů podle podmínek DÚ.
2. Nemá-li již VO aktivní členy ani aktivní správce, správce DÚ může data po 6 měsících mazat (odstavec 4 c) - chceme to takto i u repozitáře nebo bychom chtěli data trvale zachovávat nebo to nechat na rozhodnutí správce dané VO/kolekce? Pro dokumentový NR jsme chtěli trvale uchovávat data, pokud nebude majitel dat proti. 
3. Zánik členství uživatele ve VO (odstavec 4 b) - znepřístupnění a následné mazání jeho dat po 6 měsících - týká se to uložených dat nebo jen jeho osobních dat připojených k účtu? Viz bod 2, pokud se jedná o uložená data.

**Comment by david-antos** [comment]
ad 1: to se specialni sluzby vubec netyka, protoze podle bodu 2b jsme spravcem VO my (coz je juristicka fikce)
ad 2: muze, nikoli musi. A obecne vzato trvam na tom, ze mame mit tohle pravo (ze ho nebudeme vyuzivat, pokud jsou to rozumna data, je jina vec). Ale uzivatele maji existovat a kolekce mit kuratora.
ad 3: ulozenych dat a je to tak spravne.
