### ISSUE TITLE
Aktualizace taxonomie Funders

### ISSUE THREAD

**Issue by petulica** [Narodni-repozitar/nr-issues#34]
K poskytovatelům byly přidány identifikátory ROR
nový soubor: [funders_AKTUALIZOVANO.xlsx](https://github.com/Narodni-repozitar/nr-issues/files/7089942/funders_AKTUALIZOVANO.xlsx)

**Comment by mirekys** [comment]
Aktualizovano v https://github.com/Narodni-repozitar/nr-taxonomies/pull/12
