### ISSUE TITLE
Odmazani vybranych poli ve vkladacim formulari

### ISSUE THREAD

**Issue by milkydan** [Narodni-repozitar/nr-issues#42]
Ve vkladacim formulari nefunguje odmazani vybranych polozek z taxonomie pomoci krizku dole mezi vybranymi polozkami (oznaceno cervene), smazani je mozne jen pomoci od-kliknuti zatrzitka u dane polozky. Stejne se to chova i u ostatnich formularu napriklad afiliace.
![image](https://user-images.githubusercontent.com/24695997/135250772-ca727ac0-4641-4fe4-b779-e33dd8609270.png)

**Comment by mirekys** [comment]
Fixed in https://github.com/Narodni-repozitar/nr-ui/pull/7/commits/7cece480f522c98017cbc71c929b6c664acfa691
