### ISSUE TITLE
Chybejici popisek pro vyber afiliace u autoru

### ISSUE THREAD

**Issue by milkydan** [Narodni-repozitar/nr-issues#43]
Vyber funguje, ale nevidim, co vybiram. Pak je tam jeste bug, co sem reportoval [tady](https://github.com/Narodni-repozitar/nr-issues/issues/42), ze nefunguje ten maly krizek pro odebrani jiz vybranych polozek.

![image](https://user-images.githubusercontent.com/24695997/135252877-eb070552-a1fb-4652-b3ef-a236676de8be.png)

**Comment by mirekys** [comment]
Zajimave, v taxonomii institutions nam na testu zmizel sloupec title, je tam jen fullName, ktery se nepouziva k zobrazeni

**Comment by mirekys** [comment]
**UPDATE**: do stavajici taxonomie institutions se pridaji byvale sloupky `title_cs` a `title_en`

**Comment by hanavyc** [comment]
[institutions_AKTUALIZOVANO_DATApilot_oprava.xlsx](https://github.com/Narodni-repozitar/nr-issues/files/7251783/institutions_AKTUALIZOVANO_DATApilot_oprava.xlsx)

Přidány sloupce title_cs a title_en se zkopírovanými hodnotami ze sloupců fullname a name_translated.

**Comment by mirekys** [comment]
Oprava nasazena na nr-testu
