### ISSUE TITLE
Vyber oborove kategorie - vyhledavani

### ISSUE THREAD

**Issue by milkydan** [Narodni-repozitar/nr-issues#44]
Nefunguje mi vyber ani vyhledavani oborove kategorie. Nejde ani zadat zadny pojem.
![image](https://user-images.githubusercontent.com/24695997/135254054-3310a9cd-54f7-42c5-a347-48fbe4b119c4.png)

**Comment by milkydan** [comment]
Formular mam asi proklikany, jen mne kvuli NEmoznosti vybrat oborovou kategorii nepusti dale k vytvoreni zaznamu.

**Comment by mirekys** [comment]
Zpusobeno zapomenutim importu subjectCategories taxonomie (z nr-taxonomies) pres:
```
oarepo taxonomies import subjectCategories.xlsx
```
