### ISSUE TITLE
Uprava taxonomie resourceType

### ISSUE THREAD

**Issue by petulica** [Narodni-repozitar/nr-issues#9]
Doplnila jsem do taxonomie v excelu Other a Datasets v souladu s jinými položkami. Taky jsem smazala jeden sloupec. Je potřeba to zaktualizovat v kodu. 

[resourceType_AKTUALIZOVANO_bez_GL.xlsx](https://github.com/Narodni-repozitar/nr-issues/files/6907980/resourceType_AKTUALIZOVANO_bez_GL.xlsx)

**Comment by petulica** [comment]
takhle je ten excel definitivně připravený. podle jiných systémů jsem se rozhodla nerozlišovat typy datasetů a nevytvářet pod datasets podtypy. **ready-to-go**

**Comment by mirekys** [comment]
@petulica prosim jeste o doplneni typologie dle dnesniho callu, pak bych nasadil do [nr-taxonomies](https://github.com/NarodniRepozitar/nr-taxonomies)

**Comment by hanavyc** [comment]
Nová verze taxonomie doplněná o položky k RelationItem, oprava drobností i u dalších položek. Je potřeba znovu nasadit. [resourceType_AKTUALIZOVANO_bez_GL_v2.xlsx](https://github.com/Narodni-repozitar/nr-issues/files/6945506/resourceType_AKTUALIZOVANO_bez_GL_v2.xlsx)
